sonar.projectKey=AltaPay_sdk-python_307c8b3c-eb03-4e95-8a4f-3cb5510110a9

# Ignore Sonar rule: Property names should match ^[a-z][a-zA-Z0-9]*$
sonar.issue.ignore.multicriteria=e1,e2,e3
sonar.issue.ignore.multicriteria.e1.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e1.resourceKey=altapay/utils.py
sonar.issue.ignore.multicriteria.e2.ruleKey=python:S3776
sonar.issue.ignore.multicriteria.e2.resourceKey=altapay/utils.py
sonar.issue.ignore.multicriteria.e3.ruleKey=python:S1192
sonar.issue.ignore.multicriteria.e3.resourceKey=docs/conf.py
