# This workflow will install Python dependencies, run flake8, isort and integration tests with tox

name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.9]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Conda Python ${{ matrix.python-version }}
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: testenv
          python-version: ${{ matrix.python-version }}
          auto-update-conda: true
          auto-activate-base: false
          use-mamba: true

      - name: Install dependencies
        run: |
          conda run -n testenv python -m pip install --upgrade pip
          conda run -n testenv pip install responses requests six isort flake8 nose tox

      - name: Create config for integration tests
        run: |
          echo altapay_account="${{secrets.GATEWAYUSER}}" > __init__.py
          echo altapay_password="${{secrets.GATEWAYPASS}}" >> __init__.py
          echo altapay_url="${{secrets.GATEWAYURL}}/merchant/" >> __init__.py
          echo altapay_test_terminal_name="${{secrets.CC_TERMINAL_NAME}}" >> __init__.py
          echo altapay_invoice_test_terminal_name="${{ secrets.INVOICE_TERMINAL_NAME}}" >> __init__.py
          echo altapay_contract_identifier="${{ secrets.GATEWAY_CONTRACT_IDENTIFIER }}" >> __init__.py
        working-directory: tests/integration  

      - name: Run tests with tox
        run: |
          conda run -n testenv tox
