# This workflow will install Python dependencies, run flake8, isort and integration tests with tox

name: Python tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.9]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install responses requests six isort flake8 nose tox

      - name: Create config for integration tests
        run: |
          echo altapay_account="${{secrets.GATEWAYUSER}}" > __init__.py 
          echo altapay_password="${{secrets.GATEWAYPASS}}" >> __init__.py
          echo altapay_url="${{secrets.GATEWAYURL}}/merchant/" >> __init__.py
          echo altapay_test_terminal_name="${{secrets.CC_TERMINAL_NAME}}" >> __init__.py
          echo altapay_invoice_test_terminal_name="${{ secrets.INVOICE_TERMINAL_NAME}}" >> __init__.py
          echo altapay_contract_identifier="${{ secrets.GATEWAY_CONTRACT_IDENTIFIER }}" >> __init__.py
        working-directory: tests/integration

      - name: Run tests
        run: tox
